#
# Compass Slaves MPUxxxx
#

obj-$(CONFIG_MPU_SENSORS_AMI306) += inv_mpu_ami306.o
inv_mpu_ami306-objs +=	ami306.o


EXTRA_CFLAGS += -Idrivers/hwmon/inv_mpu
EXTRA_CFLAGS += -D__C99_DESIGNATED_INITIALIZER
